# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0002_auto_20171222_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactmeasurement',
            name='measurement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
