# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0003_artifactmeasurement_measurement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactmeasurement',
            name='body_temperature',
        ),
        migrations.AddField(
            model_name='artifactmeasurement',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='artifactmeasurement',
            name='blood_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='artifactmeasurement',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
