# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhistory', '0005_auto_20171227_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='body_temperature',
            new_name='temperature',
        ),
    ]
