# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('month_used_calls', models.IntegerField(default=0)),
                ('available_calls', models.IntegerField(default=1)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('cmd_peru', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_specialist', models.CharField(blank=True, max_length=100, null=True)),
                ('call_activate', models.BooleanField(default=False)),
                ('in_call', models.BooleanField(default=False)),
                ('queue_count', models.IntegerField(blank=True, default=0, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('token_sinch', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.FloatField(blank=True, default=0.0, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'm'), ('f', 'f')], max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='AllergincReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allerginc_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'Reacciones Alergicas',
                'verbose_name': 'Reacción Alérgica',
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cackgrounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'Backgrounds',
                'verbose_name': 'Background',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAttention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_attentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'Atenciones de Emergencias',
                'verbose_name': 'Atención de Emergencia',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='allergic_reaction',
            field=models.ManyToManyField(blank=True, to='customuser.AllergincReaction'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='background',
            field=models.ManyToManyField(blank=True, to='customuser.Background'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='emergency_attention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customuser.EmergencyAttention'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
