# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_auto_20171228_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbackgrounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
