# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.IntegerField(blank=True, null=True)),
                ('qualification_feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendation', models.IntegerField(blank=True, null=True)),
                ('recommendation_feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctors', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
