# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-created',), 'verbose_name': 'Calificacion', 'verbose_name_plural': 'Calificacion a los Doctores'},
        ),
    ]
