# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True, unique=True)),
                ('calls_quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('plan_culqi_id', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('patients', models.ManyToManyField(blank=True, null=True, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
