# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20171227_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('name',)},
        ),
    ]
